name: better_pro_assignment
description: "A resilient Flutter transaction system implementing Clean Architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Network
  dio: ^5.4.3+1
  
  # DI
  get_it: ^7.7.0
  injectable: ^2.4.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  uuid: ^4.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  path_provider: ^2.1.3

  # Code Gen Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generators
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
